services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/mydatabase"
      JWT_SECRET: "senhafoda"
    depends_on:
      - postgres
    networks:
      - postgres_network
   
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge